// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class DialogResponse {
    "Path": string;
    "Error": any;

    /** Creates a new DialogResponse instance. */
    constructor($$source: Partial<DialogResponse> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Error" in $$source)) {
            this["Error"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DialogResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): DialogResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DialogResponse($$parsedSource as Partial<DialogResponse>);
    }
}
