name: Release Pipeline for macOS intel

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install system dependencies
        run: |
          brew update
          brew install gtk+3

      # Windows dependencies can be added here if needed

      - name: Install wails3 cli
        run: go install github.com/wailsapp/wails/v3/cmd/wails3@v3.0.0-alpha.9

      - name: Build Wails app
        run: wails3 package

      - name: Create DMG from .app
        run: |
          hdiutil create -volname "http-file-share" -srcfolder "bin/http-file-share.app" -ov -format UDZO "bin/http-file-share-intel.dmg"

      - name: Upload build artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: bin/http-file-share-x86.dmg
